### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by MrTimscampi** [Zastai/MetaBrainz.MusicBrainz.CoverArt#17]
Hi, I'm part of the [Jellyfin project](https://github.com/jellyfin).

I'm looking at using this, along with `MetaBrainz.MusicBrainz` for our Cover Art Archive and Music Brainz plugins, respectively.

However, while NuGet mentions the license as MS-PL (for both packages), there doesn't seem to be any mentions of licenses in the actual repos.

Is the MS-PL license correct? If not, what is the code licensed under?

Thanks in advance.

**Comment by Zastai** [comment]
Yes, it's correct.
But you're right, I should it as LICENSE.md to the repos to make it clearer that the same applies to the sources on GitHub.

**Comment by MrTimscampi** [comment]
Thanks for the quick answer :smiley:

**Comment by MrTimscampi** [comment]
Looking at it, it seems like MS-PL is incompatible with the GPL, which means that we unfortunately wouldn't be able to use it: https://www.gnu.org/licenses/license-list.html#ms-pl

I may be overstepping a little here, but would you give some thought about re-licensing the libraries to something like MIT? (Which is also used by most .NET Core projects like the framework itself, ASP.NET and other parts of the ecosystem, and is actually compatible with the GPL)

**Comment by Zastai** [comment]
I'll think about it.

**Comment by ismay** [comment]
> I started the process a while back, adjusting the licenses of the root projects and working up to the projects that depend on them. But work has been quite busy so my brainspace has been limited. I will probably try to push out releases around the net6.0 release; those would be under the new license then.

Great, that's good to hear. Thanks for the hard work, it's appreciated!

**Comment by Zastai** [comment]
The default branch is now on MIT. Release will take a little bit longer, because I'll have to switch the code to use `HttpClient` (was already doing that in the ListenBrainz library, so not a huge endeavour).

The main MusicBrainz library will get the same treatment, but that's a massive codebase in comparison so will take longer to process (as part of the SDK upgrade and `net6.0` support I'm switching everything to file-scoped namespaces and making the use of braces more consistent).

**Comment by Zastai** [comment]
Fixed in v4.0.0.
